'use client';

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';

/**
 * Export report to PDF
 * @param {Object} report - The report object
 * @param {string} filename - Output filename (without extension)
 */
export async function exportToPDF(report, filename = 'report') {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPosition = margin;

  // Helper to add new page if needed
  const checkNewPage = (requiredSpace = 20) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
    }
  };

  // Title
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  const titleLines = pdf.splitTextToSize(report.title, contentWidth);
  pdf.text(titleLines, margin, yPosition);
  yPosition += titleLines.length * 10 + 5;

  // Metadata
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 100, 100);
  pdf.text(`Template: ${report.templateId} • Status: ${report.status}`, margin, yPosition);
  yPosition += 8;

  if (report.metadata?.totalWordCount) {
    pdf.text(`${report.metadata.totalWordCount.toLocaleString()} words`, margin, yPosition);
    yPosition += 8;
  }

  // Separator line
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Sections
  pdf.setTextColor(0, 0, 0);
  
  for (const section of report.sections) {
    checkNewPage(30);

    // Section heading
    const isSubSection = section.number.includes('.');
    pdf.setFontSize(isSubSection ? 12 : 14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${section.number} ${section.title}`, margin + (isSubSection ? 5 : 0), yPosition);
    yPosition += isSubSection ? 6 : 8;

    // Section content
    if (section.content) {
      pdf.setFontSize(11);
      pdf.setFont('times', 'normal');
      
      // Strip HTML tags and convert to plain text
      const plainText = section.content
        .replace(/<br\s*\/?>/gi, '\n')
        .replace(/<[^>]+>/g, '')
        .replace(/&nbsp;/g, ' ')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .trim();

      const contentLines = pdf.splitTextToSize(plainText, contentWidth - (isSubSection ? 5 : 0));
      
      for (const line of contentLines) {
        checkNewPage(6);
        pdf.text(line, margin + (isSubSection ? 5 : 0), yPosition);
        yPosition += 5;
      }
    } else {
      pdf.setFontSize(10);
      pdf.setFont('times', 'italic');
      pdf.setTextColor(150, 150, 150);
      pdf.text('No content yet.', margin + (isSubSection ? 5 : 0), yPosition);
      pdf.setTextColor(0, 0, 0);
      yPosition += 5;
    }

    yPosition += 8;
  }

  // Footer on last page
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text(
    `Generated by AutoReport • ${new Date().toLocaleDateString()}`,
    margin,
    pageHeight - 10
  );

  // Save
  pdf.save(`${filename}.pdf`);
}

/**
 * Export report to DOCX
 * @param {Object} report - The report object
 * @param {string} filename - Output filename (without extension)
 */
export async function exportToDOCX(report, filename = 'report') {
  const children = [];

  // Title
  children.push(
    new Paragraph({
      text: report.title,
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    })
  );

  // Metadata
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Template: ${report.templateId} • Status: ${report.status}`,
          size: 20,
          color: '666666',
        }),
      ],
      spacing: { after: 100 },
    })
  );

  if (report.metadata?.totalWordCount) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${report.metadata.totalWordCount.toLocaleString()} words`,
            size: 20,
            color: '666666',
          }),
        ],
        spacing: { after: 400 },
      })
    );
  }

  // Sections
  for (const section of report.sections) {
    const isSubSection = section.number.includes('.');

    // Section heading
    children.push(
      new Paragraph({
        text: `${section.number} ${section.title}`,
        heading: isSubSection ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_1,
        spacing: { before: 300, after: 100 },
      })
    );

    // Section content
    if (section.content) {
      // Strip HTML and convert to plain text
      const plainText = section.content
        .replace(/<br\s*\/?>/gi, '\n')
        .replace(/<[^>]+>/g, '')
        .replace(/&nbsp;/g, ' ')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .trim();

      // Split by newlines to create paragraphs
      const paragraphs = plainText.split('\n').filter(p => p.trim());
      
      for (const para of paragraphs) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: para,
                size: 24, // 12pt
                font: 'Times New Roman',
              }),
            ],
            spacing: { after: 120 },
          })
        );
      }
    } else {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: 'No content yet.',
              italics: true,
              color: '999999',
              size: 22,
            }),
          ],
          spacing: { after: 120 },
        })
      );
    }
  }

  // Footer
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by AutoReport • ${new Date().toLocaleDateString()}`,
          size: 18,
          color: '999999',
        }),
      ],
      spacing: { before: 600 },
      alignment: AlignmentType.CENTER,
    })
  );

  // Create document
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: children,
      },
    ],
  });

  // Generate and save
  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${filename}.docx`);
}

/**
 * Export report to DOC (same as DOCX for simplicity)
 * Note: .doc is legacy format, modern systems open .docx
 */
export async function exportToDOC(report, filename = 'report') {
  // Use DOCX format but save with .doc extension
  // Most modern Word versions can open .docx files
  const children = [];

  // Title
  children.push(
    new Paragraph({
      text: report.title,
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    })
  );

  // Metadata
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Template: ${report.templateId} • Status: ${report.status}`,
          size: 20,
          color: '666666',
        }),
      ],
      spacing: { after: 400 },
    })
  );

  // Sections
  for (const section of report.sections) {
    const isSubSection = section.number.includes('.');

    children.push(
      new Paragraph({
        text: `${section.number} ${section.title}`,
        heading: isSubSection ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_1,
        spacing: { before: 300, after: 100 },
      })
    );

    if (section.content) {
      const plainText = section.content
        .replace(/<br\s*\/?>/gi, '\n')
        .replace(/<[^>]+>/g, '')
        .replace(/&nbsp;/g, ' ')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .trim();

      const paragraphs = plainText.split('\n').filter(p => p.trim());
      
      for (const para of paragraphs) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: para,
                size: 24,
                font: 'Times New Roman',
              }),
            ],
            spacing: { after: 120 },
          })
        );
      }
    }
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${filename}.doc`);
}
